apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debug
  name: debug
spec:
  containers:
  - image: xxradar/hackon
    args:
    - bash
    - -c
    - "echo test >/output/succeeded.txt"
    name: debug
    volumeMounts:
    - name: myvolume
      mountPath: /output
  volumes:
  - name: myvolume
    hostPath:
      path: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
