apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarhack-ingress
spec:
  rules:
  - host: demo.ns.dockersec.me
    http:
      paths:
      - backend:
          serviceName: my-radarhack-clusterip
          servicePort: 80
